// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieAppsContext))]
    partial class MovieAppsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.AppResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action",
                            Director = "Jon Watts",
                            Edited = false,
                            Lent = "",
                            Notes = "Best Movie",
                            Rating = "PG-13",
                            Title = "Spider-Man: No Way Home",
                            Year = "2021"
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Television",
                            Director = "Jason Sudeikis Bill, Lawrence Brendan, Hunt Joe Kelly",
                            Edited = false,
                            Lent = "",
                            Notes = "Best TV Show",
                            Rating = "PG-13",
                            Title = "Ted Lasso",
                            Year = "2020"
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Comedy",
                            Director = "Brian Helgeland",
                            Edited = false,
                            Lent = "",
                            Notes = "Classic",
                            Rating = "PG-13",
                            Title = "A Knights Tale",
                            Year = "2001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
